### ISSUE TITLE
Parse organizer & attendees

### ISSUE THREAD

**Issue by itswillta** [linagora/dav-parser#3]
Currently there's no `organizer` and/or `attendees` properties in `CalendarEventObject`. These properties are needed to display information about the organizer and attendees of an event, for example:

![image](https://user-images.githubusercontent.com/24670327/114993581-2405b880-9ec6-11eb-9589-d99dc98cdc32.png)

**Comment by rezk2ll** [comment]
@huy-ta the organizer and attendees properties do exist in the calendarEventObject

the attendees are available in `calendarEventObject.attendees` and the organizer is available in `calendarEventObject.extendedProps.organizer` as a string.

**Comment by itswillta** [comment]
My bad. I didn't notice it. I'll close the issue.
